# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoPEC - Software científico para avaliação da acurácia posicional em  
 dados cartográficos
 GeoPEC - Scientific software for assessing positional accuracy in 
 spatial data
 
 
 Structure generated by "Plugin Builder"
 Licensed under GNU version 3


 Script que faz a ligação entre o design gráfico (Qt designer) e o código
 A script that connects the graphic design (Qt designer) and the code.

 
 autores: Afonso P. Santos; João Vítor A. Gonçalves; Luis Philippe Ventura
 email: afonso.santos@ufv.br
 ***************************************************************************/
"""

import os

from PyQt6 import uic
from PyQt6 import QtWidgets

# carrega o arquivo .ui com a parte grafica elaborada pelo Qt Designer e 'armazena' no FORM_CLASS 
# Load the .ui file containing the graphical elements created by Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'gerarentrada_qt.ui'))


class gerarentradaDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        # inicializa a classe para garantir que a janela seja criada corretamente no sistema operacional
        # Initializes the class to ensure the window is created correctly in the operating system.
        super(gerarentradaDialog, self).__init__(parent)
        # Pega todos os elementos gráficos do arquivo .ui e coloca dentro da janela
        # Takes all the graphical elements from the .ui file and places them inside the window
        self.setupUi(self)
