# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoPEC - Software científico para avaliação da acurácia posicional em  
 dados cartográficos
 GeoPEC - Scientific software for assessing positional accuracy in 
 spatial data


 Structure generated by "Plugin Builder"
 Licensed under GNU version 3

 
 Gera arquivo de entrada para o software GeoPEC desktop v3.6
 A partir de duas camadas (teste e referência) é realizada um spatial join 
 entre as camadas e gerado um arquivo txt com as coordenadas de teste e 
 referencia dos pontos homologos
 Generates an input file for the GeoPEC desktop v3.6 software.
 From two layers (test and reference), a spatial join is performed between 
 the layers and a text file is generated with the test and reference 
 coordinates of the homologous points.

 
 autores: Afonso P. Santos; João Vítor A. Gonçalves; Luis Philippe Ventura
 email: afonso.santos@ufv.br
 ***************************************************************************/
"""

from PyQt6.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, QVariant
from PyQt6.QtGui import QIcon, QAction
from PyQt6.QtWidgets import QFileDialog, QMessageBox
from qgis.core import *
from osgeo import gdal

# Initialize Qt resources from file resources.py
from ..resources import *

# Import the code for the dialog
from ..gui.gerarentrada_dialog import gerarentradaDialog

import processing
import os.path
import math


class gerarentrada:
    """Gerar arquivo de entrada TXT para o GeoPEC Desktop"""
    """Generates an input file for the GeoPEC desktop"""

    def __init__(self, iface):
        # Pega o caminho do diretório onde o arquivo atual está localizado
        # Get the path to the directory where the current file is located.
        current_dir = os.path.dirname(os.path.abspath(__file__))

        # Sobe um nível na hierarquia de diretórios para chegar à pasta principal
        # Go up one level in the directory hierarchy to reach the main folder.
        self.plugin_dir = os.path.dirname(current_dir)       
        
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir,'i18n','pec_{}.qm'.format(locale))
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)
            
        # Configurando métodos para não aparecer janelas de erro mais de uma vez
        # Configuring methods to prevent error windows from appearing more than once.
        self.first_start = True
        self.connections_made = False 
        
        # Save reference to the QGIS interface
        self.iface = iface
   
        self.dlg = gerarentradaDialog()
        
        # Ativando métodos de atualização dos combo_Box quando uma layer é adicionada ou removida do projeto
        # Enabling combo_Box update methods when a layer is added to or removed from the project.
        QgsProject.instance().layersAdded.connect(self.carregaVetor)
        QgsProject.instance().layersRemoved.connect(self.carregaVetor)
                  
    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('gerarentrada', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        pass
        
    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        self.iface.mainWindow().menuBar().removeAction(self.menu.menuAction())
        del self.menu
        # remove the toolbar
        del self.toolbar

    def carregaVetor(self):
        """Preenche os combobox com as layers vetoriais do tipo ponto"""
        """Fill the comboboxes with vector layers of the point type"""
        
        # limpando os comboBox
        # cleaning the comboBoxes
        self.dlg.comboBox.clear()
        self.dlg.comboBox_2.clear()
        
        # obtendo as instâncias do projeto
        # Obtaining project instances
        project = QgsProject.instance()
        
        # obtendo as layers
        # get layers
        layers = project.mapLayers()
        
        # obtendo somente as layers de pontos
        # get only points layers
        point_layers = []
        
        for layer in layers.values():
        
            if layer.type() == QgsMapLayerType.VectorLayer and layer.geometryType() == QgsWkbTypes.PointGeometry:
                point_layers.append(layer)
        
        # Obtendo os nomes das camadas de pontos
        # # Obtaining the names of the point layers
        point_layer_names = [layer.name() for layer in point_layers]

        # Preenchendo  os ComboBoxes
        # fill combobox
        self.dlg.comboBox.addItems(point_layer_names)
        self.dlg.comboBox_2.addItems(point_layer_names)

    def carregaCamada(self):
        """execução do botão para abrir uma layer. Será aberto uma janela de diálogo e a layer escolhida será adicionada ao projeto e ao combobox"""
        """Clicking the button to open a layer will open a dialog box, and the selected layer will be added to the project and the combobox."""

        camada_abrir = str(QFileDialog.getOpenFileName(caption = "Escolha a camada",filter = "Shapefiles (*.shp)")[0])
    
        if camada_abrir:
    
            # Carregar a camada
            # load layer
            layer = QgsVectorLayer(camada_abrir, str.split(os.path.basename(camada_abrir), ".") [0], "ogr")
        
            # Verificando se a camada possui geometria de ponto
            # Checking if the layer has point geometry
            if layer.geometryType() == QgsWkbTypes.PointGeometry:
                # Adicionar a camada ao projeto
                # Add the layer to the project
                QgsProject.instance().addMapLayer(layer)
                self.carregaVetor()
            else:
            # Informar ao usuário que a camada não possui geometria de ponto
            # Inform the user that the layer does not contain point geometry.
                QMessageBox.warning(self.dlg, "Erro", "A camada selecionada não possui geometria de ponto.")
                pass
    
    def obt_data(self):
        """Método que extrai os dados das camadas de teste e de referência, faz a junção espacial e gera uma estrutura para salvar os dados necessários"""
        """Method that extracts data from the test and reference layers, performs spatial joining, and generates a structure to save the necessary data"""

        # Obtendo o nome das camadas de teste e de referência
        # Obtaining the names of the test and reference layers
        nome_pt_teste = self.dlg.comboBox.currentText()
        nome_pt_ref = self.dlg.comboBox_2.currentText()
        
        # Obtendo as camadas pelo nome
        # get the layers by name
        pt_teste = QgsProject.instance().mapLayersByName(nome_pt_teste)[0]
        pt_ref = QgsProject.instance().mapLayersByName(nome_pt_ref)[0]
        
        # Criando cópias temporárias das camadas de teste e de referência
        # create a clone of the test and reference layers     
        self.pt_teste = pt_teste.clone()
        self.pt_ref = pt_ref.clone()
                
        # Verificando se as camadas têm o mesmo SRC
        # Checking if the layers have the same SRC
        crs_teste = self.pt_teste.crs()
        crs_ref = self.pt_ref.crs()
        if not crs_teste == crs_ref:
            return False
        
        # Removendo todos os atributos das camadas temporárias
        # remove all attributes of clone layers
        fields_test_names = [field.name() for field in self.pt_teste.fields()]
        self.pt_teste.dataProvider().deleteAttributes([self.pt_teste.fields().indexFromName(name) for name in fields_test_names])

        fields_ref_names = [field.name() for field in self.pt_ref.fields()]
        self.pt_ref.dataProvider().deleteAttributes([self.pt_ref.fields().indexFromName(name) for name in fields_ref_names])

    
        # Adicionando os novos atributos às camadas temporárias
        # Adding the new attributes to the temporary layers
        fields_test = [
            QgsField("IDt", QVariant.Int),
            QgsField("Xxtest", QVariant.Double),
            QgsField("Yytest", QVariant.Double),
            QgsField("Zztest", QVariant.Double),
        ]
        
        fields_ref = [
            QgsField("IDr", QVariant.Int),
            QgsField("Xxref", QVariant.Double),
            QgsField("Yyref", QVariant.Double),
            QgsField("Zzref", QVariant.Double),
        ]
        
        self.pt_teste.dataProvider().addAttributes(fields_test)
        self.pt_ref.dataProvider().addAttributes(fields_ref)
    
        # Atualizando os campos das camadas
        # Updating layer fields
        self.pt_teste.updateFields()
        self.pt_ref.updateFields()
  
        # calculando os campos X Y Z
        # calculating the X Y Z fields
        self.pt_teste.startEditing()
        numb = 1
        for ft in self.pt_teste.getFeatures():
            self.pt_teste.changeAttributeValue(ft.id(), self.pt_teste.fields().indexFromName("IDt"), numb)
            self.pt_teste.changeAttributeValue(ft.id(), self.pt_teste.fields().indexFromName("Xxtest"), ft.geometry().asPoint().x())
            self.pt_teste.changeAttributeValue(ft.id(), self.pt_teste.fields().indexFromName("Yytest"), ft.geometry().asPoint().y())
            self.pt_teste.changeAttributeValue(ft.id(), self.pt_teste.fields().indexFromName("Zztest"), ft.geometry().vertexAt(0).z())
            
            numb += 1
        self.pt_teste.commitChanges()

        self.pt_ref.startEditing()

        nn = 1
        for fr in self.pt_ref.getFeatures():
            self.pt_ref.changeAttributeValue(fr.id(), self.pt_ref.fields().indexFromName("IDr"), nn)
            self.pt_ref.changeAttributeValue(fr.id(), self.pt_ref.fields().indexFromName("Xxref"), fr.geometry().asPoint().x())
            self.pt_ref.changeAttributeValue(fr.id(), self.pt_ref.fields().indexFromName("Yyref"), fr.geometry().asPoint().y())
            self.pt_ref.changeAttributeValue(fr.id(), self.pt_ref.fields().indexFromName("Zzref"), fr.geometry().vertexAt(0).z())
            
            nn += 1
        self.pt_ref.commitChanges()
        
        # Realizando o spatial join para juntar os dados de teste e de referência
        # Considera pontos homólogos os pontos mais próximos entre o conjunto dos dados de teste e de referência
        # OBS: Caso o produto possua um efeito sistemático de grande magnitude, esta metodologia de definição de pontos homólogos não será eficiente

        # Performing a spatial join to combine test and reference data
        # Consider homologous points to be the closest points between the test and reference data sets
        # NOTE: If the product has a large-magnitude systematic effect, this methodology for defining homologous points will not be efficient
        algresult  = processing.run("qgis:joinbynearest", {
                'DISCARD_NONMATCHING' : True, 
                'FIELDS_TO_COPY' : [], 
                'INPUT' : self.pt_teste, 
                'INPUT_2' : self.pt_ref, 
                'MAX_DISTANCE' : None, 
                'NEIGHBORS' : 1, 
                'OUTPUT' : 'memory:JOIN', 
                'PREFIX' : '' })
                
        self.join = algresult['OUTPUT']
        
        # Manipulando os dados do spatial join para gerar uma estrutura com os dados necessário para gerar o arquivo TXT
        # Manipulating the spatial join data to generate a structure with the necessary data to generate the TXT file.
        data = []
        for f in self.join.getFeatures():   
            dict_valores = { "IDt" : f["IDt"],
                            "Xxtest": f["Xxtest"],
                            "Yytest" : f["Yytest"],
                            "Zztest" : f["Zztest"],
                            "Xxref" : f["Xxref"],
                            "Yyref" : f["Yyref"],
                            "Zzref" : f["Zzref"]}
            
            for pt in dict_valores.keys():      
                # Verificando se existem dados nan ou NULL, caso existam, são substituídos por 0
                # Checking if nan or NULL data exists; if so, it is replaced with 0.
                comp = str(dict_valores[pt])
                
                if  (comp == 'nan' or comp == 'NULL'):
                    dict_valores[pt] = 0
                
                else:
                    pass            
            
            idd, xt, yt, zt, xr, yr, zr = dict_valores["IDt"], dict_valores["Xxtest"], dict_valores["Yytest"], dict_valores["Zztest"], dict_valores["Xxref"], dict_valores["Yyref"], dict_valores["Zzref"]
            data.append(f"{idd}\t{xt}\t{yt}\t{zt}\t{xr}\t{yr}\t{zr}")
  
        # Apagando as camadas temporárias e o join
        # Deleting join and temporary layers
        del self.join 
        del self.pt_teste
        del self.pt_ref   
                
            
        return data
        
    def abrir_caminho(self):
        """execução do botão para definir o local e o nome do arquivo TXT"""
        """Execution of the button to set the location and name of the TXT file"""

        # Abrir uma caixa de diálogo para salvar o arquivo de saída
        # Open a dialog box to save the output file
        file_path, _ = QFileDialog.getSaveFileName(self.dlg, "Salvar arquivo", "", "Arquivos de Texto (*.txt);;Todos os Arquivos (*.*)")
        self.dlg.lineEdit.setText(file_path)
        pass

    def gerar_arquivo(self):
        """Método que gera o arquivo TXT de entrada do GeoPEC Desktop"""
        """Method that generates the GeoPEC Desktop input TXT file"""

        # Verifica se ambos os comboboxes possuem alguma seleção
        # Check if both combo boxes have any selections.
        if not self.dlg.comboBox.currentText() or not self.dlg.comboBox_2.currentText():
            QMessageBox.warning(self.dlg, "Aviso", "Por favor, selecione as camadas de Teste e Referência nos campos correspondentes.")
            return
        
        # Obtendo o caminho do LineEdit
        # get LineEdit path
        file_path = self.dlg.lineEdit.text()
        if not file_path:
            QMessageBox.warning(self.dlg, "Aviso", "Por favor, defina o local e o nome do arquivo de saída clicando no botão '...'")
            return
        
        # Obtendo os dados para salvar no relatório
        # Obtaining the data to save in the report
        data = self.obt_data()
      
        # Escrevendo os dados no arquivo
        # writing data in file
        if data:
            try:
                with open(file_path, 'w') as file:
                    for line in data:
                        file.write(line + '\n')
                    
                QMessageBox.information(self.dlg, "Sucesso", "Arquivo gerado com sucesso.")
            except Exception as e:
                QMessageBox.critical(self.dlg, 'Erro', f'Erro ao gravar o arquivo no disco: {str(e)}')
        else:
            # Caso o obt_data retorne False ou lista vazia
            # If obt_data returns False or an empty list
            QMessageBox.critical(self.dlg, 'Erro', 'Não foi possível gerar o arquivo de entrada, confira se há dados nas camadas e também se possuem o mesmo SRC.') 

    def run(self):
        """Execute o método que realiza todo o trabalho"""
        """Run method that performs all the real work"""
        
        if not self.connections_made:
            # chama a janela de dialogo
            # show the dialog
            self.carregaVetor()
            
            # Conectando os botões às funções 
            # Connecting the buttons to the functions
            self.dlg.pushButton.clicked.connect(self.carregaCamada)
            self.dlg.pushButton_2.clicked.connect(self.carregaCamada)
            self.dlg.pushButton_3.clicked.connect(self.abrir_caminho)
            self.dlg.pushButton_4.clicked.connect(self.gerar_arquivo)
             
            # Marcar como conectado
            self.connections_made = True 
        
        self.dlg.show()
	