# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoPEC - Software científico para avaliação da acurácia posicional em  
 dados cartográficos
 GeoPEC - Scientific software for assessing positional accuracy in 
 spatial data


 Structure generated by "Plugin Builder"
 Licensed under GNU version 3

 
 Analisa o padrão de distribuição espacial pelo método do vizinho mais próximo
 para feições pontuais
 Analyzes the spatial distribution pattern using the nearest neighbor method 
 for point features.
 
 autores: Afonso P. Santos; João Vítor A. Gonçalves; Luis Philippe Ventura
 email: afonso.santos@ufv.br
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon, QAction
from qgis.PyQt.QtWidgets import QFileDialog, QMessageBox, QLabel
from qgis.core import *
from ..resources import *

# Import the code for the dialog
from ..gui.padraodistribuicao_dialog import padraodistribuicaoDialog

import os.path
import os

# Importando as funções implementadas em functions/calc_dist_esp.py
# Importing the functions implemented in functions/alc_dist_esp.py
from ..functions.calc_dist_esp import *


class padraodistribuicao:
    """Implementação do padrão de distribuição espacial pelo método do vizinho mais próximo para feições pontuais"""
    """Implementation of the spatial distribution pattern using the nearest neighbor method for point features"""

    def __init__(self, iface):
        # Pega o caminho do diretório onde o arquivo atual está localizado
        # Get the path to the directory where the current file is located.
        current_dir = os.path.dirname(os.path.abspath(__file__))
        
        # Sobe um nível na hierarquia de diretórios para chegar à pasta principal
        # Go up one level in the directory hierarchy to reach the main folder.
        self.plugin_dir = os.path.dirname(current_dir)
        
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir,'i18n','pec_{}.qm'.format(locale))
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)
                
        # Save reference to the QGIS interface
        self.iface = iface 
        self.dlg = padraodistribuicaoDialog()

        # Configurando métodos para não aparecer janelas de erro mais de uma vez
        # Configuring methods to prevent error windows from appearing more than once.      
        self.first_start = True    
        self.connections_made = False  
        
        # Ativando métodos de atualização dos combo_Box quando uma layer é adicionada ou removida do projeto
        # Enabling combo_Box update methods when a layer is added to or removed from the project.
        QgsProject.instance().layersAdded.connect(self.carregaPonto)
        QgsProject.instance().layersRemoved.connect(self.carregaPonto)
        QgsProject.instance().layersAdded.connect(self.carregaPoligono)
        QgsProject.instance().layersRemoved.connect(self.carregaPoligono)
        
    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('padraodistribuicao', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action
    
    def initGui(self):
        pass

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        self.iface.mainWindow().menuBar().removeAction(self.menu.menuAction())
        del self.menu
        # remove the toolbar
        del self.toolbar

    def carregaPonto(self):
        """Preenche os combobox com as layers vetoriais do tipo ponto"""
        """Fill the comboboxes with vector layers of the point type"""

        # limpando os comboBox do conjunto de Pontos
        # clear combobox
        self.dlg.comboBox_3.clear()
        
        # obtendo as instâncias do projeto
        # Obtaining project instances
        project = QgsProject.instance()
        
        # obtendo as layers
        # get layers
        layers = project.mapLayers()
        
        # obtendo somente as layers de pontos
        # get only points layers
        point_layers = []
        for layer in layers.values():
            if layer.type() == QgsMapLayerType.VectorLayer and layer.geometryType() == QgsWkbTypes.PointGeometry:
                point_layers.append(layer)
        
        # Adicionando as layers de pontos ao comboBox correspondente
        # Adding the point layers to the corresponding comboBox.
        for layer in point_layers:
            self.dlg.comboBox_3.addItem(layer.name(), layer)
        
    def procuraPonto(self):
        """Execução do botão para abrir uma layer de ponto. Será aberto uma janela de diálogo e a layer escolhida será adicionada ao projeto e ao combobox"""
        """Clicking the button to open a point layer will open a dialog box, and the selected layer will be added to the project and the combobox."""
        
        camada_abrir = str(QFileDialog.getOpenFileName(caption = "Escolha a camada",filter = "Shapefiles (*.shp)")[0])
        if camada_abrir:
            # Carregar a camada 
            # load layer      
            layer = QgsVectorLayer(camada_abrir, str.split(os.path.basename(camada_abrir), ".") [0], "ogr")

            # Verificando se a camada possui geometria de ponto
            # Checking if the layer has point geometry
            if layer.geometryType() == QgsWkbTypes.PointGeometry:
            
                # Adicionar a camada ao projeto
                # Add the layer to the project
                QgsProject.instance().addMapLayer(layer)
                
                # Atualiza o comboBox ao vetor escolhido
                # update combobox
                self.carregaPonto()
                self.dlg.comboBox_3.addItem(layer.name(), layer)
                index = self.dlg.comboBox_3.findText(layer.name())
                if index != -1:
                    self.dlg.comboBox_3.setCurrentIndex(index)
                    
            else:
                # Informar ao usuário que a camada não possui geometria de ponto
                # Inform the user that the layer does not contain point geometry
                self.show_messagebox_erro('erro', 'A camada selecionada não possui geometria de ponto')

    def carregaPoligono(self):
        """Preenche os combobox_8, quando habilitado com as layers vetoriais do tipo polígono"""
        """Fills combobox_8, when enabled, with vector layers of type polygon"""
        
        # limpando os comboBox do Conjunto de Polígonos
        # clear combobox
        self.dlg.comboBox_8.clear()
        
        # obtendo as instâncias do projeto
        # Obtaining project instances
        project = QgsProject.instance()
        
        # obtendo as layers
        # get layers
        layers = project.mapLayers()
        
        # obtendo somente as layers de polígonos
        # get only polygon layers
        polygon_layers = []
        
        # garantindo que as camada adicionadas são do tipo poligono
        # ensuring that the added layers are of the polygon type
        for layer in layers.values():
            if layer.type() == QgsMapLayerType.VectorLayer and layer.geometryType() == QgsWkbTypes.PolygonGeometry:
                polygon_layers.append(layer)
        
        # Adicionando as layers de polígonos ao comboBox
        # Adding the polygon layers to the corresponding comboBox.
        for layer in polygon_layers:
            self.dlg.comboBox_8.addItem(layer.name(), layer)

    def procuraPoligono(self):
        """execução do botão para abrir uma layer do tipo polígono. Será aberto uma janela de diálogo e a layer escolhida será adicionada ao projeto e ao combobox_8"""
        """Clicking the button opens a polygon layer. A dialog box will open, and the selected layer will be added to the project and to combobox_8"""

        camada_abrir = str(QFileDialog.getOpenFileName(caption = "Escolha a camada",filter = "Shapefiles (*.shp)")[0])
        if camada_abrir:
    
            # Carregar a camada
            # load layer 
            layer = QgsVectorLayer(camada_abrir, str.split(os.path.basename(camada_abrir), ".") [0], "ogr")
        
            # Verificando se a camada possui geometria de polígono
            # Checking if the layer has polygon geometry
            if layer.geometryType() == QgsWkbTypes.PolygonGeometry:
            
                # Adicionar a camada ao projeto
                # Add the layer to the project
                QgsProject.instance().addMapLayer(layer)
                
                # Atualiza o comboBox ao vetor escolhido
                # update combobox
                self.carregaPoligono()
                self.dlg.comboBox_8.addItem(layer.name(), layer)               
                index = self.dlg.comboBox_8.findText(layer.name())               
                if index != -1:
                    self.dlg.comboBox_8.setCurrentIndex(index)
                    
            else:
                # Informar ao usuário que a camada não possui geometria de polígono
                # Inform the user that the layer does not contain polygon geometry.
                self.show_messagebox_erro('erro', 'A camada selecionada não possui geometria de polígono.')
                
    def calculaArea(self, _=None):
        """Obtém as informações referentes à Área de Estudo ou calcula a geometria"""
        """Get the Study Area or calculates the geometry"""
        
        area = 0

        # Define o nível de confiança
        # set confiance level
        nivel_confianca = self.defineNC()


        # Definição manual do valor de área
        # Manually defining the area value
        if self.dlg.radioButton.isChecked():
            try:
                # Permite a vírgula como separador decimal
                # Allows the use of a comma as a decimal separator (brazilian standard)
                valor_area = self.dlg.lineEdit.text().replace(',', '.')
                valor_area = float(valor_area)
                
            except ValueError:
                self.show_messagebox_erro('erro', 'Por favor, insira um valor numérico válido para a área.')
                return None
            
            unidade = self.dlg.comboBox_7.currentText()
            
            # Transformação de unidades --> levando para m²
            # Unit conversion --> converting to m²
            if unidade == 'ha':
                area = valor_area * 10000
            elif unidade == 'km²':
                area = valor_area * 1000000
            else:
                area = valor_area


        # Definição do valor de área pelo retângulo envolvente do conjunto de pontos
        # Defining the area value using the rectangle that encloses the set of points
        elif self.dlg.radioButton_2.isChecked():
            layer_name = self.dlg.comboBox_3.currentText()
            if not layer_name:  
                self.show_messagebox_erro('erro', 'Por favor, selecione uma camada de pontos.')
                return None
            
            layers = QgsProject.instance().mapLayersByName(layer_name)
            if not layers:  
                self.show_messagebox_erro('erro', 'Camada de pontos não encontrada.')
                return None
            
            # extraindo a extensão espacial dos dados pontuais e calculando a área
            # Extracting the spatial extent from point data and calculating the area.
            layer = layers[0]
            extent = layer.extent()
            area = extent.width() * extent.height()
        

        # Definição do valor de área a partir de uma layer de polígono escolhido pelo usuário
        # Defining the area value from a user-selected polygon layer
        elif self.dlg.radioButton_3.isChecked():
            layer_name = self.dlg.comboBox_8.currentText()  
            if not layer_name:       
                self.show_messagebox_erro('erro', 'Por favor, selecione uma camada de polígonos.')      
                return None

            layers = QgsProject.instance().mapLayersByName(layer_name)
            if not layers:    
                self.show_messagebox_erro('erro', 'Camada de polígonos não encontrada.')
                return None

            layer = layers[0]
            if layer.geometryType() != QgsWkbTypes.PolygonGeometry:    
                self.show_messagebox_erro('erro', 'A camada selecionada não possui geometria de polígono.')  
                return None

            # Verificar se há mais de um polígono na camada
            # Check if there is more than one polygon in the layer
            num_polygons = sum(1 for _ in layer.getFeatures())         
            if num_polygons != 1:   
                self.show_messagebox_erro('erro', 'A camada (layer) selecionada deve conter uma única feição de polígono.')
                return None

            # Calcular a área se a camada tem apenas 1 polígono
            # Calculate the area if the layer has only 1 polygon.
            for feature in layer.getFeatures():
                geom = feature.geometry()
                area += geom.area()

        # Caso de a área ser nula ou negativa
        # If the area is zero or negative
        if area <= 0:
            self.show_messagebox_erro('erro', 'Resultado inválido para área. Por favor, verifique as entradas.')
            return None


        # resultado da área a ser retornado pela função
        # result of the area to be returned by the function 
        return area
            
    def habilitaArea(self):
        """Desabilita ou habilita as ferramentas gráficas, dependendo da seleção do usuário quanto ao tipo de área que será utilizado"""
        """Disables or enables graphic tools, depending on the user's selection of the type of area to be used"""

        self.dlg.radioButton.toggled.connect(self.atualizaWidgets)
        self.dlg.radioButton_2.toggled.connect(self.atualizaWidgets)
        self.dlg.radioButton_3.toggled.connect(self.atualizaWidgets)
        
        # Desabilita todos os widgets no início, quando ainda não há seleção de radioButton
        # Disables all widgets at startup, when no radioButton is selected yet.
        self.atualizaWidgets()
        
    def atualizaWidgets(self):
        """Desabilita as ferramentas não necessárias dependendo da seleção de toolButton do usuário, servindo de apoio para a função habilitaArea"""
        """Disables unnecessary tools depending on the user's toolButton selection, serving as support for the habilitaArea function"""
        
        # Se a definição manual da área for ativada
        # If manual area definition is enabled
        if self.dlg.radioButton.isChecked():
            self.dlg.lineEdit.setEnabled(True)
            self.dlg.comboBox_7.setEnabled(True)
            self.dlg.comboBox_8.setEnabled(False)
            self.dlg.toolButton_2.setEnabled(False)
            
        # Se a definição da área for por retângulo envolvente
        # If the area is defined by an enclosing rectangle
        elif self.dlg.radioButton_2.isChecked():
            self.dlg.lineEdit.setEnabled(False)
            self.dlg.comboBox_7.setEnabled(False)
            self.dlg.comboBox_8.setEnabled(False)
            self.dlg.toolButton_2.setEnabled(False)
            
        # Se a definição da área for por uma camada de polígono 
        # If the area is defined by a polygon layer
        elif self.dlg.radioButton_3.isChecked():
            self.dlg.lineEdit.setEnabled(False)
            self.dlg.comboBox_7.setEnabled(False)
            self.dlg.comboBox_8.setEnabled(True)
            self.dlg.toolButton_2.setEnabled(True)
            
         # Se não houver nenhuma das 3 definições anteriores, todos ficam desabilitados
        # If none of the three previous settings are present, all are disabled.
        else:
            self.dlg.lineEdit.setEnabled(False)
            self.dlg.comboBox_7.setEnabled(False)
            self.dlg.comboBox_8.setEnabled(False)
            self.dlg.toolButton_2.setEnabled(False)
      
    def atualizaComboBoxes(self):
        """Atualiza os comboBox_3 e comboBox_8 com base nas camadas no QGIS"""
        """Updates comboBox_3 and comboBox_8 based on the layers in QGIS"""
        
        comboBox_3 = self.dlg.comboBox_3
        comboBox_8 = self.dlg.comboBox_8

        # Limpar os comboboxes referentes a ponto e polígono, respectivamente
        # Clear the combo boxes related to point and polygon, respectively.
        comboBox_3.clear()
        comboBox_8.clear()

        # Iterar sobre todas as camadas no QGIS
        # Iterate over all layers in QGIS
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() == QgsMapLayer.VectorLayer:
                if layer.geometryType() == QgsWkbTypes.PointGeometry:
                    comboBox_3.addItem(layer.name(), layer)
                elif layer.geometryType() == QgsWkbTypes.PolygonGeometry:
                    comboBox_8.addItem(layer.name(), layer)
    
    def defineNC(self):
        """Lê o nível de confiança do comboBox_9 e retorna a escolha do usuário"""
        """Reads the confidence level of comboBox_9 and returns the user's choice"""

        nivel_confianca = self.dlg.comboBox_9.currentText()
        
    def insereResultado(self):
        """Insere os resultados calculados nas labels específicas"""
        """Inserts the calculated results into the specified labels"""
        
        # Chama a função calculaArea para obter a área
        # Calls the "calculateArea" function to obtain the area
        area = self.calculaArea()       
        if area is None:
            return

        # Chama a função fCalculaEstatistica para obter os resultados
        # Calls the "fCalculaEstatistica" function to obtain the results
        resultados = fCalculaEstatistica(self.dlg, area)
        if resultados is None:
            return

        try: 
            # Desempacotando os resultados calculados em fCalculaEstatistica
            # Unpacking the results calculated in "fCalculaEstatistica"
            (R_primeira_ordem, R_segunda_ordem, R_terceira_ordem,
             r_obs_primeira_ordem, r_obs_segunda_ordem, r_obs_terceira_ordem,
             r_esperado_primeira_ordem, r_esperado_segunda_ordem, r_esperado_terceira_ordem,
             Zcalculado_primeira_ordem, Zcalculado_segunda_ordem, Zcalculado_terceira_ordem,
             SE_r_primeira_ordem, SE_r_segunda_ordem, SE_r_terceira_ordem,
             padrao_primeira_ordem, padrao_segunda_ordem, padrao_terceira_ordem,
             significancia_primeira_ordem, significancia_segunda_ordem, significancia_terceira_ordem,
             Ztabelado, nivel_confianca,
             padrao_final_primeira_ordem, padrao_final_segunda_ordem, padrao_final_terceira_ordem) = resultados

            # Função para determinar a significância estatística
            # Function to determine statistical significance
            def determinaSignificancia(Zcalculado, Ztabelado):
                if abs(Zcalculado) > Ztabelado:
                    return "(significativo estatisticamente)"
                else:
                    return "(NÃO é significativo estatisticamente)"
            

            # Função para formatar números com vírgula como separador decimal, tendo 4 casas decimais
            # Function to format numbers using a comma as the decimal separator, with 4 decimal places
            def formataResultado4c(number):
                return f"{number:.4f}".replace('.', ',')
            
            # Função para formatar números com vírgula como separador decimal, tendo 2 casas decimais
            # Function to format numbers using a comma as the decimal separator, with 2 decimal places
            def formataResultado2c(number):
                return f"{number:.2f}".replace('.', ',')
            
            # Atualização das labels para a primeira ordem
            # Updating labels for the first order
            self.dlg.label_31.setText(formataResultado4c(r_obs_primeira_ordem))
            self.dlg.label_32.setText(formataResultado4c(r_esperado_primeira_ordem))
            self.dlg.label_33.setText(formataResultado4c(R_primeira_ordem))
            self.dlg.label_34.setText(formataResultado4c(Zcalculado_primeira_ordem))
            self.dlg.label_35.setText(formataResultado4c(SE_r_primeira_ordem))
            self.dlg.label_36.setText(formataResultado2c(Ztabelado))
            self.dlg.label_56.setText(formataResultado4c(area))
            self.dlg.label_37.setText(padrao_primeira_ordem)
            self.dlg.label_38.setText(significancia_primeira_ordem)

            # Atualização das labels para a segunda ordem
            # Updating labels for the second order
            self.dlg.label_43.setText(formataResultado4c(r_obs_segunda_ordem))
            self.dlg.label_44.setText(formataResultado4c(r_esperado_segunda_ordem))
            self.dlg.label_45.setText(formataResultado4c(R_segunda_ordem))
            self.dlg.label_46.setText(formataResultado4c(Zcalculado_segunda_ordem))
            self.dlg.label_47.setText(formataResultado4c(SE_r_segunda_ordem))
            self.dlg.label_41.setText(padrao_segunda_ordem)
            self.dlg.label_39.setText(significancia_segunda_ordem)

             # Atualização das labels para a terceira ordem
             # Updating labels for the third order
            self.dlg.label_48.setText(formataResultado4c(r_obs_terceira_ordem))
            self.dlg.label_49.setText(formataResultado4c(r_esperado_terceira_ordem))
            self.dlg.label_50.setText(formataResultado4c(R_terceira_ordem))
            self.dlg.label_51.setText(formataResultado4c(Zcalculado_terceira_ordem))
            self.dlg.label_52.setText(formataResultado4c(SE_r_terceira_ordem))
            self.dlg.label_42.setText(padrao_terceira_ordem)
            self.dlg.label_40.setText(significancia_terceira_ordem)

            # Exibindo resultados finais, destacados na cor vermelha, na última linha
            # Displaying final results, highlighted in red, on the last line
            self.dlg.label_57.setText(padrao_final_primeira_ordem)
            self.dlg.label_58.setText(padrao_final_segunda_ordem)
            self.dlg.label_59.setText(padrao_final_terceira_ordem)
            
            # Mudar automaticamente para a segunda aba do tabWidget, a aba de resultados
            # Automatically switch to the second tab of the tabWidget, the results tab
            self.dlg.tabWidget.setCurrentIndex(1)

        except ValueError as e:
            self.show_messagebox_erro('erro', 'Erro ao processar resultados.')

    def show_messagebox_erro(self, tipo, mensagem):
        """Janela de Error"""
        """Error Dialog"""

        # error message
        if  (tipo == 'erro'):     
            # Crie uma instância do QMessageBox
            # Create an instance of QMessageBox
            msg_box = QMessageBox()

            # Defina o ícone da janela
            # Define the window icon
            msg_box.setWindowIcon(QIcon(self.plugin_dir + "/icon/geopec.png"))  

            # Configure a mensagem de erro
            # Configure the error message
            msg_box.setIcon(QMessageBox.Icon.Critical)
            msg_box.setWindowTitle('Erro')
            msg_box.setText(mensagem)

            # Exiba a mensagem
            # show message
            msg_box.exec()
        
        # sucess message    
        else: 
            
            # Crie uma instância do QMessageBox
            # Create an instance of QMessageBox
            msg_box = QMessageBox()

            # Defina o ícone da janela
            # Define the window icon
            msg_box.setWindowIcon(QIcon(self.plugin_dir + "/icon/geopec.png"))  

            # Configure a mensagem de sucesso
            # Configure the sucess message
            msg_box.setIcon(QMessageBox.Icon.Information)
            msg_box.setWindowTitle('Sucesso')
            msg_box.setText(mensagem)

            # Exiba a mensagem
            # show message
            msg_box.exec()
        
    def generateRelatorio(self):
        """ Método para gerar o relatório"""
        """ Method for generating the report"""

        try:
            # Obtém o valor da área
            # get area value
            area = self.calculaArea()
            if area is None:
                return
                 
            # Obtém os resultados calculados
            # get results
            resultados = fCalculaEstatistica(self.dlg, area)
            if resultados is None:
                return
                
            # chama a função de gerar o relatório "fGeraRelatorio"
            # calls the function to generate the report "fGeraRelatorio"
            fGeraRelatorio(resultados)

        except:
            # erro message
            msg_box = QMessageBox()
            msg_box.setWindowTitle('Erro')  
            msg_box.setText('Ocorreu um erro durante o processamento.')  
            msg_box.exec() 
        
    def run(self):
        """Execute o método que realiza todo o trabalho"""
        """Run method that performs all the real work"""

        if self.first_start:
            self.first_start = False
            # chama a janela de dialogo
            # show the dialog
            self.dlg = padraodistribuicaoDialog()

        # certifica que as conexões serão feitas uma única vez
        # ensures that connections will be made only once
        if not self.connections_made:
            
            # Chamando as funções de carregar ponto e poligono e calcular area
            # Calling the functions to load a point and a polygon, and to calculate the area.
            self.carregaPonto()
            self.dlg.toolButton.clicked.connect(self.procuraPonto)
            self.habilitaArea()
            self.carregaPoligono()
            self.dlg.toolButton_2.clicked.connect(self.procuraPoligono)
           
            # Conectar o botão para calcular estatísticas e inserir resultados
            # button to calculate statistics and insert results
            self.dlg.pushButton.clicked.connect(self.insereResultado)
            
            # Conecta o botão para gerar relatório
            # button to generate report
            self.dlg.pushButton_2.clicked.connect(self.generateRelatorio)
            
            # Marcar as conexões como feitas
            # Mark the connections as made
            self.connections_made = True

        # Atualiza os comboboxes antes de mostrar o diálogo
        # update combobox before displaying the dialog
        self.atualizaComboBoxes()

        # show the dialog
        self.dlg.show()

