# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoPEC - Software científico para avaliação da acurácia posicional em  
 dados cartográficos
 GeoPEC - Scientific software for assessing positional accuracy in 
 spatial data


 Structure generated by "Plugin Builder"
 Licensed under GNU version 3

 
 Sobre o plugin
 About the plugin

 
 autores: Afonso P. Santos; João Vítor A. Gonçalves; Luis Philippe Ventura
 email: afonso.santos@ufv.br
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from qgis.PyQt.QtGui import QIcon, QAction
from qgis.PyQt.QtWidgets import QFileDialog
from qgis.core import *
from osgeo import gdal

# Initialize Qt resources from file resources.py
from ..resources import *

# Import the code for the dialog
from ..gui.sobre_dialog import sobreDialog

import processing
import os.path
import math
import os
import platform
import subprocess

class sobre:
    """Classe relativa à janela "Sobre" o plugin"""
    """Class related to the "About" window of the plugin"""

    def __init__(self, iface):
        # Pega o caminho do diretório onde o arquivo atual está localizado
        # Get the path to the directory where the current file is located.
        current_dir = os.path.dirname(os.path.abspath(__file__))
        
        # Sobe um nível na hierarquia de diretórios para chegar à pasta principal
        # Go up one level in the directory hierarchy to reach the main folder.
        self.plugin_dir = os.path.dirname(current_dir)
        
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir,'i18n','pec_{}.qm'.format(locale))
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)
                
        # Save reference to the QGIS interface
        self.iface = iface
        self.dlg = sobreDialog()

        # Configurando métodos para não aparecer janelas de erro mais de uma vez
        # Configuring methods to prevent error windows from appearing more than once.
        self.first_start = True
        self.connections_made = False  
        
    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('tamanhoamostral', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        pass
        
    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        self.iface.mainWindow().menuBar().removeAction(self.menu.menuAction())
        del self.menu
        # remove the toolbar
        del self.toolbar
   
    def open_pdf(self):
        """Método para abrir os termos de uso"""
        """Method for opening the terms of use"""

        file_path = self.plugin_dir + "/docs/Termos_de_uso_plugin_geopec.pdf"
        
        try:
            if platform.system() == 'Windows':
                os.startfile(file_path)
            elif platform.system() == 'Darwin':  # macOS
                subprocess.call(('open', file_path))
            else:  # Linux
                subprocess.call(('xdg-open', file_path))
            
        except:
            self.show_messagebox_erro("erro", "Não foi possível abrir os termos de uso do programa!")
    
    def show_messagebox_erro(self, tipo, mensagem):
        """Método para exibir um messagebox informando erro ou sucesso em alguma ação do programa"""    
        """Method to display a messagebox informing of an error or success in some action"""

        # tipo de mensagem: erro
        # message type: error        
        if  (tipo == 'erro'): 
        
            # Create a QMessageBox instance
            msg_box = QMessageBox()

            # set icon
            msg_box.setWindowIcon(QIcon(self.plugin_dir + "/icon/geopec.png"))  

            # Configure a mensagem de erro
            # set the erro message
            msg_box.setIcon(QMessageBox.Icon.Critical)
            msg_box.setWindowTitle('Erro')
            msg_box.setText(mensagem)

            # Exibindo a mensagem
            # show message
            msg_box.exec()
        
        # tipo de menssagem: sucesso    
        # sucess message
        else: 
            
           # Create a QMessageBox instance
            msg_box = QMessageBox()

            # set icon
            msg_box.setWindowIcon(QIcon(self.plugin_dir + "/icon/geopec.png"))  

            # Configurando a mensagem de sucesso
            # set the sucess message
            msg_box.setIcon(QMessageBox.Icon.Information)
            msg_box.setWindowTitle('Sucesso')
            msg_box.setText(mensagem)

            # Exibindo a mensagem
            # show message
            msg_box.exec()
    
    def run(self):
        """Execute o método que realiza todo o trabalho"""
        """Run method that performs all the real work"""
        
        if not self.connections_made:
            self.dlg.pushButton.clicked.connect(self.open_pdf)
            self.connections_made = True    
        self.dlg.show()
	